# Tic Tac Toe





## Set up

In [2]:
import numpy as np
import pyprind
import csv

In [ ]:


np.array_equal(a, a, equal_nan=True)
QPlayer1 = []
QPlayer2 = []

np.NaN
#Loop through QPlayer matrix to see if the states exists
# If it doesnt exists then append it
for i in range(len(QPlayer1)):
    QPlayer1[i]==board
    
    
    
#Make a loop 



x = numpy.array([1,0,2,0,3,0,4,5,6,7,8])
numpy.where(x == 0)[0]
#array([1, 3, 5])


np.random.choice(5, 3)
#array([0, 3, 4]) # random

        
def takeAction(Qplayer, state, eps):
    
    #Get the state or initialize it
    for i in range(len(QPlayer)):
        if np.array_equal(QPlayer[i][0], state, equal_nan=True):
            index = i
            break;
        else:
            index = i
            QPlayer.append(state)
    
    #Eps greedy move
    if random.random() < 1-eps :
        curr_action = np.argmax(QPlayer[index][2])
        
    else:
        numpy.where(x == 0)[0]
        np.random.choice(5, 3)
        
        curr_action = 0 if random.random() < 0.5 else 1;
        
    
    
            
    return;



In [6]:

#State,Qmatrix is a numpy array
#Each index contains State and QMatrix
#QPlayer1 = [ list(State1,QMatrix1) , list(State2,QMatrix2) ... ]

InitialState = np.zeros(9)
ExpectedReward = np.zeros(9)

QPlayer1 = [[InitialState, ExpectedReward]]
QPlayer2 = []

alpha = .01
gamma = 1


for episodes in pyprind.prog_bar(range(10000)):
    if episodes%1000==0:
        print("Number of iterations: {}".format(episodes))
        eps = eps/2
    #Reset board
    State = np.zeros((3,3))
    
    #Loop until game ends
    while True:
            
        ######## First player ########
        #Take action according to greedy eps policy
        stateIndex, state ,nextStateIndex, action,r, terminal = takeAction(QPlayer1,state, eps)
            
        #Q-learning update
        QPlayer1[stateIndex][2][action] = QPlayer1[stateIndex][2][action] + alpha*(r+gamma*np.max(QPlayer1[nextState][2]) - QPlayer1[stateIndex][2][action])

        state = nextState
        if terminal:
            break;
                
        ######## Second player ########
        #Take action according to greedy eps policy
        nextState, r, t = takeAction(QPlayer2,state)
            
        #Q-learning update
        QPlayer2[s,a] = QPlayer2[s,a] + alpha*(r+gamma*np.max(QPlayer2[nextState]) - QPlayer2[s,a])
            
        state = nextState
        if t==True:
            break;
                
                

                

    



for QPlayer in (QPlayer1, QPlayer2):
    Top = np.array([s[0].reshape(3,3) for s in QPlayer])
    Bottom = np.array([s[1].reshape(3,3) for s in QPlayer])
    QPlayer = np.array([Top, Bottom])
    np.savetxt("QPlayer1.csv", QPlayer, delimiter=",")
    

'''            
#Reformat lists
data_list = [["SN", "Name", "Contribution"],
             [1, "Linus Torvalds", "Linux Kernel"],
             [2, "Tim Berners-Lee", "World Wide Web"],
             [3, "Guido van Rossum", "Python Programming"]]


#export to CSV
with open('QPlayer1.csv', 'w', newline='') as file:
    writer = csv.writer(file, delimiter='|')
    writer.writerows(data_list)
'''

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
Number of iterations: 0


NameError: name 'eps' is not defined

In [18]:

QPlayer = [[np.arange(9), np.ones(9)], [np.arange(9),np.ones(9)]]



QPlayer = [np.concatenate([s[0].reshape(3,3), s[1].reshape(3,3)], axis=0) for s in QPlayer]
QPlayer = np.concatenate(QPlayer, axis=1)
print(QPlayer)
np.savetxt("QPlayer1.csv", QPlayer, delimiter=",")


[[0. 1. 2. 0. 1. 2.]
 [3. 4. 5. 3. 4. 5.]
 [6. 7. 8. 6. 7. 8.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
